USE [master]
GO
/****** Object:  Database [myComicShop]    Script Date: 10/11/2022 7:42:00 PM ******/
CREATE DATABASE [myComicShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'myComicShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\myComicShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'myComicShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\myComicShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [myComicShop] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myComicShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [myComicShop] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [myComicShop] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [myComicShop] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [myComicShop] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [myComicShop] SET ARITHABORT OFF 
GO
ALTER DATABASE [myComicShop] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [myComicShop] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [myComicShop] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [myComicShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [myComicShop] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [myComicShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [myComicShop] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [myComicShop] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [myComicShop] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [myComicShop] SET  ENABLE_BROKER 
GO
ALTER DATABASE [myComicShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [myComicShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [myComicShop] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [myComicShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [myComicShop] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [myComicShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [myComicShop] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [myComicShop] SET RECOVERY FULL 
GO
ALTER DATABASE [myComicShop] SET  MULTI_USER 
GO
ALTER DATABASE [myComicShop] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [myComicShop] SET DB_CHAINING OFF 
GO
ALTER DATABASE [myComicShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [myComicShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [myComicShop] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [myComicShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'myComicShop', N'ON'
GO
ALTER DATABASE [myComicShop] SET QUERY_STORE = OFF
GO
USE [myComicShop]
GO
/****** Object:  Table [dbo].[Comics]    Script Date: 10/11/2022 7:42:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comics](
	[ComicID] [int] NOT NULL,
	[Title] [varchar](200) NOT NULL,
	[Writer] [varchar](100) NOT NULL,
	[Artist] [varchar](50) NULL,
	[Publisher] [varchar](50) NULL,
	[IssuePages] [varchar](4) NULL,
	[Price] [money] NULL,
PRIMARY KEY CLUSTERED 
(
	[ComicID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 10/11/2022 7:42:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[ID] [int] NOT NULL,
	[CustName] [varchar](50) NOT NULL,
	[HomeAddress] [varchar](30) NOT NULL,
	[Zipcode] [varchar](10) NOT NULL,
	[Phone] [varchar](15) NULL,
	[Membership] [varchar](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Locations]    Script Date: 10/11/2022 7:42:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[ID] [int] NOT NULL,
	[Name] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetails]    Script Date: 10/11/2022 7:42:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetails](
	[ID] [int] NOT NULL,
	[OrderID] [int] NOT NULL,
	[Stock] [int] NOT NULL,
	[QTY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PendingOrders]    Script Date: 10/11/2022 7:42:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PendingOrders](
	[ID] [int] NOT NULL,
	[LocationID] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
	[OrderDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Zipcode]    Script Date: 10/11/2022 7:42:00 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Zipcode](
	[Zipcode] [varchar](10) NOT NULL,
	[City] [varchar](30) NOT NULL,
	[State] [varchar](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Zipcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_Zipcode]    Script Date: 10/11/2022 7:42:00 PM ******/
CREATE NONCLUSTERED INDEX [idx_Zipcode] ON [dbo].[Customers]
(
	[Zipcode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_OrderID]    Script Date: 10/11/2022 7:42:00 PM ******/
CREATE NONCLUSTERED INDEX [idx_OrderID] ON [dbo].[OrderDetails]
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Stock]    Script Date: 10/11/2022 7:42:00 PM ******/
CREATE NONCLUSTERED INDEX [idx_Stock] ON [dbo].[OrderDetails]
(
	[Stock] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Customer]    Script Date: 10/11/2022 7:42:00 PM ******/
CREATE NONCLUSTERED INDEX [idx_Customer] ON [dbo].[PendingOrders]
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_Location]    Script Date: 10/11/2022 7:42:00 PM ******/
CREATE NONCLUSTERED INDEX [idx_Location] ON [dbo].[PendingOrders]
(
	[LocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customers]  WITH CHECK ADD  CONSTRAINT [FK_Zipcode] FOREIGN KEY([Zipcode])
REFERENCES [dbo].[Zipcode] ([Zipcode])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Zipcode]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderID] FOREIGN KEY([OrderID])
REFERENCES [dbo].[PendingOrders] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderID]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_Stock] FOREIGN KEY([Stock])
REFERENCES [dbo].[Comics] ([ComicID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_Stock]
GO
ALTER TABLE [dbo].[PendingOrders]  WITH CHECK ADD  CONSTRAINT [FK_CustomerID] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PendingOrders] CHECK CONSTRAINT [FK_CustomerID]
GO
ALTER TABLE [dbo].[PendingOrders]  WITH CHECK ADD  CONSTRAINT [FK_LocationID] FOREIGN KEY([LocationID])
REFERENCES [dbo].[Locations] ([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PendingOrders] CHECK CONSTRAINT [FK_LocationID]
GO
USE [master]
GO
ALTER DATABASE [myComicShop] SET  READ_WRITE 
GO
